baseURL = "/"
languageCode = "en-us"
relativeURLs = "true"
title = "Starořecký jazyk"
theme = "lanyon"
publishDir = "docs"

[params]
  author = "Martin Masliš"
  description = "Navigace"
  title = "Starořecký jazyk"

[outputs]
     home = [ "HTML", "JSON" ]
